---
# File Name: test.gardnersnake_rnaseq_basic.yaml
# Created By: ZW
# Created On: 2022-05-03
# Purpose: dummy gardner extended configuration for rnaseq workflow

# first yaml doc contains schema for generic workflow configurations
analysis_id: "test-gardner-rnaseq"
workdir: '.'
rule_params:
  - {
    rule_name: "Verify_Index_Contents",
    resources: {
      walltime: "00:10:00",
      nodes: 1,
      processors_per_node: 1,
      total_memory: 2000,
      log_dir: "logs/",
      job_id: ''
    },
    parameters: {
      genome_index_manifest: [
        "Genome", "chrLength.txt", "exonGeTrInfo.tab", "sjdbInfo.txt",
        "Log.out", "chrName.txt", "exonInfo.tab", "sjdbList.fromGTF.out.tab",
        "SA", "chrNameLength.txt", "geneInfo.tab", "sjdbList.out.tab",
        "SAindex", "chrStart.txt", "genomeParameters.txt", "transcriptInfo.tab"
      ]
    }
  }

---
# second yaml doc contains schema for metadata (sequencing files, etc.)
shared_data:
  libraries: [
    {
      library_name: "lib-1",
      runs: [
        {
          run_name: "run-1-1",
          fastq1: "run-1-1.fastq.gz",
          fastq2: null
        }
      ]
    },
    {
      library_name: "lib-2",
      runs: [
        {
          run_name: "run-2-1",
          fastq1: "run-2-1.fastq.gz",
          fastq2: null
        }
      ]
    },
    {
      library_name: "lib-3",
      runs: [
        {
          run_name: "run-3-1",
          fastq1: "run-3-1.fastq.gz",
          fastq2: null
        }
      ]
    }
  ]
rule_data: [
  {
    rule_name: "Verify_Index_Contents",
    inputs: {
      genome_index_dir: "/path/to/directory"
    },
    outputs: {
      rc_out: "/path/to/verify_index_contents.rc.out"
    }
  },
  {
    rule_name: "STAR_Create_Genome_Index"
  }
]

